from selenium.webdriver.common.by import By

class PurchasingElements:
    BTN_PHONE = (By.XPATH, "/html/body/div[1]/nav/div[2]/ul/li[6]/a")
    PRODUCT_PHONE = (By.XPATH, "/html/body/div[2]/div/div/div[2]/div[1]/div/div[1]/a/img")
    BTN_ADD_CART = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/button")
    BTN_ITEMS_CART = (By.XPATH, "/html/body/header/div/div/div[3]/div/button/span")
    BTN_VIEW_CART = (By.XPATH, "/html/body/header/div/div/div[3]/div/ul/li[2]/div/p/a[1]/strong")
    BTN_CHECKOUT = (By.XPATH, "/html/body/div[2]/div/div/div[3]/div[2]/a")
    CHECK_GUEST_CHECKOUT = (By.XPATH, "/html/body/div[2]/div/div/div/div[1]/div[2]/div/div/div[1]/div[2]/label/input")
    BTN_CONTINUE_CHECKOUT = (By.XPATH, "/html/body/div[2]/div/div/div/div[1]/div[2]/div/div/div[1]/input")
    TXT_FIRST_NAME = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[1]/fieldset/div[2]/input")
    TXT_LAST_NAME = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[1]/fieldset/div[3]/input")
    TXT_EMAIL = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[1]/fieldset/div[4]/input")
    TXT_TELEPHONE = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[1]/fieldset/div[5]/input")
    TXT_COMPANY = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[1]/input")
    TXT_ADDRESS1 = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[2]/input")
    TXT_ADDRESS2 = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[3]/input")
    TXT_CITY = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[4]/input")
    TXT_POST_CODE = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[5]/input")
    LST_COUNTRY_COLOMBIA = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[6]/select/option[52]")
    LST_REGION_STATE = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[7]/select")
    LST_REGION_STATE_BOGOTA = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div[2]/fieldset/div[7]/select/option[6]")
    BTN_CONTINUE_CUSTOMER_DATA = (By.XPATH, "/html/body/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/input")
    BTN_CONTINUE_DELIVERY_METHOD = (By.XPATH, "/html/body/div[2]/div/div/div/div[4]/div[2]/div/div[2]/div/input")
    CHECK_PAYMENT_METHOD = (By.XPATH, "/html/body/div[2]/div/div/div/div[5]/div[2]/div/div[3]/div/input[1]")
    BTN_CONTINUE_PAYMENT_METHOD = (By.XPATH, "/html/body/div[2]/div/div/div/div[5]/div[2]/div/div[3]/div/input[2]")
    BTN_CONFIRM_ORDER = (By.XPATH, "/html/body/div[2]/div/div/div/div[6]/div[2]/div/div[3]/div/input")
    MSG_ORDER_OK = (By.XPATH, "/html/body/div[2]/div/div/h1")
    BTN_CONTINUE_ORDER_OK = (By.XPATH, "/html/body/div[2]/div/div/div/div/a[@class='btn btn-primary']")